# https://docs.codecov.io/docs/codecovyml-reference

# We have
#   6 * [number of basic OS] + 2 * [number of additional OS]
# parallel jobs in ci.yml
codecov:
  notify:
    after_n_builds: 10
comment:
  after_n_builds: 10

coverage:
  range: 70..95
  round: down
  precision: 2

github_checks:
  annotations: false
