# https://docs.codecov.io/docs/codecovyml-reference

# We have 5 parallel jobs on Travis CI
codecov:
  notify:
    after_n_builds: 5
comment:
  after_n_builds: 5

coverage:
  range: 70..95
  round: down
  precision: 2

github_checks:
  annotations: false
