# https://docs.codecov.io/docs/codecovyml-reference

# We have 8 * [number of OS] parallel jobs in ci.yml
codecov:
  notify:
    after_n_builds: 8
comment:
  after_n_builds: 8

coverage:
  range: 70..95
  round: down
  precision: 2

github_checks:
  annotations: false
