# https://docs.travis-ci.com/user/languages/julia/

language: julia

julia:
  - 1 # latest 1.x.y
  - nightly

matrix:
 allow_failures:
   - julia: nightly

codecov: true
coveralls: true

os:
  - linux
  - osx

# avoid duplicate tests in PRs
branches:
  only:
    - master

notifications:
  email: false

# we could use groups to trigger multiple builds in parallel to speed-up running expensive tests
# env:
#   - GROUP=SomeGroupName

# we could install binary dependencies if necessary
# addons:
#   apt:
#     packages:
#       - gfortran

# script:
# default build script along the lines of
#   using Pkg
#   Pkg.build() # Pkg.build(; verbose = true) for Julia 1.1 and up
#   Pkg.test(coverage=true)

# submit coverage reports (enabled already above) and/or deploy docs
# after_success:
