####################################################################################################
# Simulation
equations = "mhd"
#equations = "euler"
# equations = "linearscalaradvection"
# advectionvelocity = [1.0, 1.0] # Need only for linarscalaradvection

#initial_conditions = "orszag_tang"
 initial_conditions = "constant"
surface_flux_type = "laxfriedrichs"
# sources = 
t_start = 0.0
t_end   = 0.5

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.5
n_steps_max = 10000
analysis_interval = 100


####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [0, 0]
coordinates_max = [1, 1]
initial_refinement_level = 4
# refinement_patches = [
#   {type = "box", coordinates_min = 0, coordinates_max = 16},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "conservative"
restart_interval = 100
