####################################################################################################
# Simulation
equations = "hyperbolicdiffusion"
nu = 1.0

initial_conditions = "constant"

surface_flux_type = "upwind"
sources = "poisson" 
t_start = 0.0
t_end   = 2.0

# restart = true
# restart_filename = "out/restart_000100.h5"


####################################################################################################
# Solver
solver = "dg"
N = 4 
cfl = 0.5
n_steps_max = 10000
analysis_interval = 20 

#volume_integral_type = "split_form"

####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [0, 0]
coordinates_max = [1, 1]
initial_refinement_level = 5 
# refinement_patches = [
#   {type = "box", coordinates_min = [-0.5, -0.5], coordinates_max = [0.5, 0.5]},
#   {type = "box", coordinates_min = [-0.1, -0.1], coordinates_max = [0.1, 0.1]},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 0
