####################################################################################################
# Simulation
equations = "euler"
# equations = "linearscalaradvection"
# advectionvelocity = 1.0 # Need only for linarscalaradvection

initial_conditions = "convergence_test"
# sources = 
t_start = 0.0
t_end   = 1.0


####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 1.0
n_steps_max = 10000
analysis_interval = 100


####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = -16
coordinates_max =  16
initial_refinement_level = 4
refinement_patches = [
  {type = "box", coordinates_min = 0, coordinates_max = 16},
]


####################################################################################################
# I/O
solution_interval = 20
solution_variables = "conservative"
output_format = "hdf5"
