# Simulation setup
syseqn = "euler"
initialconditions = "convergence_test"
# sources = 
# advectionvelocity = 1.0
t_start = 0.0
t_end   = 10.0

# Numerical settings
N = 3
cfl = 1.0
nstepsmax = 10000
analysis_interval = 100

# Mesh
nnodesmax = 1000
coordinates_min = -16
coordinates_max =  16
initial_refinement_level = 5

# I/O
solution_interval = 20
solution_variables = "conservative"
output_format = "hdf5"
