# Simulation setup
syseqn = "euler"
initialconditions = "convergence_test"
# sources = 
advectionvelocity = 1.0
t_start = 0.0
t_end   = 10.0

# Numerical settings
N = 3
cfl = 1.0
nstepsmax = 10000
analysis_interval = 100

# Mesh
ncells = 80
x_start = -10
x_end   =  10

# I/O
solution_interval = 5
