####################################################################################################
# Simulation
ndims = 3
equations = "CompressibleEulerEquations"
gamma = 1.66667
initial_conditions = "initial_conditions_blob"
t_start = 0.0
t_end   = 2.5
#restart = true
#restart_filename = "out/restart_001000.h5"

####################################################################################################
# Solver
solver = "dg"
polydeg = 3
cfl = 0.9
n_steps_max = 15000
shock_indicator_variable = "total_energy"
#shock_indicator_variable = "density_pressure"
#shock_indicator_variable = "pressure"
shock_alpha_max = 0.01
shock_alpha_min = 0.0001
#volume_integral_type = "shock_capturing"
#volume_integral_type = "weak_form"
volume_integral_type = "split_form"
#surface_flux = "flux_lax_friedrichs"
surface_flux = "flux_hll"
#surface_flux = "flux_hllc_hll"
#volume_flux = "flux_central"
volume_flux = "flux_ranocha"
#volume_flux = "flux_chandrashekar"
#volume_flux = "flux_shima_etal"

####################################################################################################
# Mesh
n_cells_max = 500000
coordinates_min = [-20.0, -20.0, -20.0]
coordinates_max =  [20.0, 20.0, 20.0]
initial_refinement_level = 2
 refinement_patches = [
   {type = "box", coordinates_min = [-20.0, -10.0, -10.0], coordinates_max = [-10.0, 10.0, 10.0]},
   {type = "box", coordinates_min = [-20.0, -5.0, -5.0], coordinates_max = [-10.0, 5.0, 5.0]},
   {type = "box", coordinates_min = [-17.0, -2.0, -2.0], coordinates_max = [-13.0, 2.0, 2.0]},
   {type = "box", coordinates_min = [-17.0, -2.0, -2.0], coordinates_max = [-13.0, 2.0, 2.0]},
#   {type = "box", coordinates_min = [-17.0, -2.0, -2.0], coordinates_max = [-13.0, 2.0, 2.0]},
 ]
####################################################################################################
# AMR
adapt_initial_condition = false
amr_indicator = "blob2"
amr_interval = 3
amr_alpha_max = 1.0 
amr_alpha_min = 0.0001

####################################################################################################
# I/O
# save_initial_solution = false
analysis_interval = 200
solution_interval = 200
solution_variables = "primitive"
restart_interval = 200
output_format = "hdf5"
