####################################################################################################
# Simulation
ndims = 3
equations = "CompressibleEulerEquations"
gamma = 1.66667
initial_conditions = "initial_conditions_blob"
t_start = 0.0
t_end   = 8.0
# restart = true
# restart_filename = "out/restart_000100.h5"

####################################################################################################
# Solver
solver = "dg"
polydeg = 4
cfl = 0.2
n_steps_max = 15000
analysis_interval = 100
shock_indicator_variable = "pressure"
shock_alpha_max = 0.4
shock_alpha_min = 0.0001
volume_integral_type = "shock_capturing"
#volume_integral_type = "new_trick"
#volume_integral_type = "split_form"
#volume_integral_type = "weak_form"
#volume_integral_type = "entropy_fix"
#volume_integral_type = "entropy_fix2"
surface_flux = "flux_lax_friedrichs"
#surface_flux = "flux_chandrashekar"
#surface_flux = "flux_shima_etal"
#volume_flux = "flux_shima_etal"
volume_flux = "flux_chandrashekar"
# volume_flux = "flux_central"

####################################################################################################
# Mesh
n_cells_max = 500000
coordinates_min = [-20.0, -20.0, -20.0]
coordinates_max =  [20.0, 20.0, 20.0]
initial_refinement_level = 5
 refinement_patches = [
   {type = "box", coordinates_min = [-17.0, -2.0, -2.0], coordinates_max = [-13.0, 2.0, 2.0]},
#   {type = "box", coordinates_min = [-40.0, -5.0], coordinates_max = [40.0, 5.0]},
#   {type = "box", coordinates_min = [-40.0, -5.0], coordinates_max = [40.0, 5.0]},
 ]
####################################################################################################
# AMR
amr_indicator = "blob"
amr_interval = 1
amr_alpha_max = 1.0 #0.0031
amr_alpha_min = 0.0001

####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 200
output_format = "hdf5"
