####################################################################################################
# Simulation
equations = "euler_gravity"
gamma = 2.0
initial_conditions = "initial_conditions_coupling_convergence_test"
# initial_conditions = "constant"
# surface_flux = "flux_lax_friedrichs"
# volume_flux = "flux_central"
surface_flux = "flux_chandrashekar"
volume_flux = "flux_chandrashekar"
source_terms = "source_terms_coupling_convergence_test"
t_start = 0.0
t_end   = 0.5

# restart = true
# restart_filename = "out/restart_000100.h5"

volume_integral_type = "split_form"

resid_tol = 1e-10

####################################################################################################
# Solver
solver = "dg"
N = 4
cfl = 0.5
n_steps_max = 10000
n_iterations_max = 1000
analysis_interval = 100
extra_analysis_quantities = ["energy_total","energy_kinetic","energy_internal", "energy_potential"]
save_analysis = true

####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [0.0, 0.0]
coordinates_max = [2.0, 2.0]
initial_refinement_level = 2
#periodicity = false
# refinement_patches = [
#   {type = "box", coordinates_min = 0, coordinates_max = 16},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 10
solution_variables = "primitive"
restart_interval = 100
