####################################################################################################
# Simulation
equations = "euler_gravity"
gamma = 1.6666666666666667
initial_conditions = "jeans_instability"
# initial_conditions = "constant"
surface_flux = "lax_friedrichs_flux"
sources = "harmonic"
t_start = 0.0
t_end   = 2.0

# restart = true
# restart_filename = "out/restart_000100.h5"

resid_tol = 1e-5

####################################################################################################
# Solver
solver = "dg"
N = 3
cfl = 0.5
n_steps_max = 30
n_iterations_max = 50
analysis_interval = 100

####################################################################################################
# Mesh
n_cells_max = 10000
coordinates_min = [0, 0]
coordinates_max =  [1, 1]
initial_refinement_level = 4
# refinement_patches = [
#   {type = "box", coordinates_min = 0, coordinates_max = 16},
# ]


####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 10
solution_variables = "primitive"
restart_interval = 100
